# -*- coding: utf-8 -*-
"""explainabilityforallclasses.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aI6PQzoSCrEzbGAgP4SDNdVQ2x3HfgR
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers==4.41.2 -q
!pip install torch torchvision -q
!pip install opencv-python-headless -q
!pip install Pillow -q

import os
# Check what's in your Drive
print(os.listdir("/content/drive/MyDrive"))

import os
from pathlib import Path

DRIVE_DATA_ROOT  = Path("/content/drive/MyDrive")
SINGLE_MODEL_DIR = DRIVE_DATA_ROOT / "MooProjectPipeline/timesformer-cows2"
VAL_DIR          = str(DRIVE_DATA_ROOT / "Annotations/val")

NUM_FRAMES = 12
IMAGE_SIZE = 224

CLASSES = sorted(os.listdir(VAL_DIR))
print("Classes:", CLASSES)
print("N classes:", len(CLASSES))

label2id = {c: i for i, c in enumerate(CLASSES)}
id2label = {i: c for i, c in enumerate(CLASSES)}

import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

from transformers import (
    AutoConfig,
    AutoModelForVideoClassification,
    AutoImageProcessor,
    TimesformerForVideoClassification,
    VideoMAEImageProcessor,
)
import json

# Load config
cfg = AutoConfig.from_pretrained(
    SINGLE_MODEL_DIR, local_files_only=True, trust_remote_code=True)

# Fix labels
labels_path = SINGLE_MODEL_DIR / "labels.json"
if labels_path.exists():
    with open(labels_path) as f:
        lab_map = json.load(f)

    # Handle different possible structures
    if isinstance(lab_map, dict):
        # Check if it has nested label2id/id2label keys
        if 'id2label' in lab_map:
            id2label_cfg = {int(k): v for k, v in lab_map['id2label'].items()}
        elif 'label2id' in lab_map:
            label2id_raw = lab_map['label2id']
            id2label_cfg = {int(v): k for k, v in label2id_raw.items()}
        else:
            # Try direct int conversion, skip non-int keys
            id2label_cfg = {}
            for k, v in lab_map.items():
                try:
                    id2label_cfg[int(k)] = v
                except ValueError:
                    pass
    else:
        id2label_cfg = {i: v for i, v in enumerate(lab_map)}

    cfg.id2label   = id2label_cfg
    cfg.label2id   = {v: k for k, v in id2label_cfg.items()}
    cfg.num_labels = len(id2label_cfg)
    print("Labels loaded:", cfg.id2label)
else:
    print("No labels.json — using config labels")
    cfg.id2label = {int(k): v for k, v in cfg.id2label.items()}
    cfg.label2id = {v: int(k) for k, v in cfg.id2label.items()}
    cfg.num_labels = len(cfg.id2label)
    print("Labels from config:", cfg.id2label)

# Load processor
processor = AutoImageProcessor.from_pretrained(
    SINGLE_MODEL_DIR, local_files_only=True, trust_remote_code=True)

# Load model
clf_single = TimesformerForVideoClassification.from_pretrained(
    SINGLE_MODEL_DIR,
    config=cfg,
    ignore_mismatched_sizes=True,
    local_files_only=True,
    trust_remote_code=True
).to(device).eval()

print("✅ clf_single loaded")
print("Num labels:", cfg.num_labels)

import os, cv2, glob, math, torch, numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import torch.nn.functional as F
from pathlib import Path
from transformers import AutoImageProcessor

# CONFIG
VAL_DIR  = "/content/drive/MyDrive/Annotations/val"
OUT_DIR  = Path("/content/drive/MyDrive/thesis_figures")
OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT_PATH = str(OUT_DIR / "attention_maps.png")

FRAME_IDX   = 6      # which frame to show (middle of 12-frame clip)
OVERLAY_A   = 0.50   # heatmap alpha
SIZE        = 224
OVERLAY_CLR = cv2.COLORMAP_JET

CLASSES = [
    "Drinking",
    "Feeding & Lying",
    "Feeding & Standing",
    "Lying",
    "Ruminating & Lying",
    "Ruminating & Standing",
    "Standing",
]

EXPECTED_REGION = {
    "Drinking":              "Muzzle — downward head\norientation to trough",
    "Feeding & Lying":       "Muzzle & neck —\nmanger contact",
    "Feeding & Standing":    "Muzzle & neck —\nmanger contact",
    "Lying":                 "Torso & limbs —\npostural geometry",
    "Ruminating & Lying":    "Jaw & neck —\nrhythmic mandibular motion",
    "Ruminating & Standing": "Jaw & neck —\nrhythmic mandibular motion",
    "Standing":              "Full body silhouette —\nlimb-ground stance",
}

device = next(clf_single.parameters()).device
print(f"Using device: {device}")


try:
    _ = processor
    print("Using existing processor")
except NameError:
    from transformers import AutoImageProcessor
    processor = AutoImageProcessor.from_pretrained(
        SINGLE_MODEL_DIR, local_files_only=True, trust_remote_code=True)
    print("Processor reloaded")

# ── Grad-CAM hooks
class TimeSformerGradCAM:
    def __init__(self, model):
        self.model      = model
        self.gradients  = None
        self.activations = None
        self._hooks     = []
        self._register_hooks()

    def _register_hooks(self):
        # Find last transformer encoder layer
        encoder = self.model.timesformer.encoder
        last_layer = encoder.layer[-1]

        def fwd_hook(module, inp, out):
            # out is the layer output tensor [B, N, D]
            if isinstance(out, tuple):
                self.activations = out[0].detach()
            else:
                self.activations = out.detach()

        def bwd_hook(module, grad_in, grad_out):
            if isinstance(grad_out, tuple):
                self.gradients = grad_out[0].detach()
            else:
                self.gradients = grad_out.detach()

        h1 = last_layer.register_forward_hook(fwd_hook)
        h2 = last_layer.register_full_backward_hook(bwd_hook)
        self._hooks = [h1, h2]

    def remove_hooks(self):
        for h in self._hooks:
            h.remove()

    def __call__(self, pixel_values, target_class):
        """
        pixel_values: [1, C, T, H, W] or [1, T, C, H, W]
        Returns: cam [H, W] numpy array normalised 0-1,
                 pred_label str, confidence float
        """
        self.model.eval()
        self.model.zero_grad()

        # Enable gradients
        pv = pixel_values.clone().requires_grad_(True)

        outputs = self.model(pixel_values=pv)
        logits  = outputs.logits[0]               # [num_classes]
        probs   = torch.softmax(logits, dim=0)
        pred_idx   = int(probs.argmax().item())
        confidence = float(probs[target_class].item())

        # Backprop on target class score
        score = logits[target_class]
        score.backward()

        if self.gradients is None or self.activations is None:
            print("  Warning: gradients not captured, using activations only")
            acts = self.activations          # [1, N, D]
            weights = torch.ones(acts.shape[-1], device=acts.device)
        else:
            grads   = self.gradients         # [1, N, D]
            acts    = self.activations       # [1, N, D]
            weights = grads[0].mean(dim=0)   # [D]

        # Weighted combination of activations
        cam_tokens = (acts[0] * weights.unsqueeze(0)).sum(dim=-1)  # [N]

        # Remove CLS token if present
        # TimeSformer token order: [CLS, patch_1, ..., patch_N*T]
        n_patches = (SIZE // 16) ** 2   # 196 for 224x224 with 16x16 patches
        n_frames  = NUM_FRAMES          # from config

        cam_tokens = cam_tokens[1:]     # remove CLS

        # Reshape: take spatial mean across time
        total = cam_tokens.shape[0]
        if total == n_frames * n_patches:
            cam_spatial = cam_tokens.view(n_frames, n_patches)
            cam_spatial = cam_spatial.mean(dim=0)   # [n_patches]
        else:
            # Fallback: just use all tokens
            cam_spatial = cam_tokens

        # Reshape to 2D spatial map
        h_patches = w_patches = int(math.sqrt(cam_spatial.shape[0]))
        if h_patches * w_patches != cam_spatial.shape[0]:
            h_patches = w_patches = 14  # default for 224/16

        cam_2d = cam_spatial[:h_patches*w_patches].view(h_patches, w_patches)

        # ReLU and normalise
        cam_2d = F.relu(cam_2d)
        cam_2d = cam_2d - cam_2d.min()
        cam_2d = cam_2d / (cam_2d.max() + 1e-8)

        pred_label = CLASSES[pred_idx] if pred_idx < len(CLASSES) else str(pred_idx)
        return cam_2d.cpu().numpy(), pred_label, confidence


def preprocess_frames(frames_bgr):
    frames_rgb = [cv2.cvtColor(f, cv2.COLOR_BGR2RGB) for f in frames_bgr]
    from PIL import Image
    pil_frames = [Image.fromarray(f) for f in frames_rgb]
    inputs = processor(images=pil_frames, return_tensors="pt")
    return inputs["pixel_values"].to(device)   # [1, C, T, H, W] or [1, T, C, H, W]


def read_clip(path, n_frames=None):
    if n_frames is None:
        n_frames = NUM_FRAMES
    cap = cv2.VideoCapture(path)
    all_frames = []
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        all_frames.append(frame)
    cap.release()
    if not all_frames:
        return None
    # Uniform sample
    total = len(all_frames)
    idxs  = np.linspace(0, total-1, n_frames).round().astype(int)
    return [all_frames[i] for i in idxs]


def make_overlay(frame_bgr, cam_np):
    frame_resized = cv2.resize(frame_bgr, (SIZE, SIZE))
    cam_uint8 = (cam_np * 255).astype(np.uint8)
    cam_resized = cv2.resize(cam_uint8, (SIZE, SIZE))
    heat = cv2.applyColorMap(cam_resized, OVERLAY_CLR)
    overlay = cv2.addWeighted(frame_resized, 1.0 - OVERLAY_A, heat, OVERLAY_A, 0)
    return cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)


#  Instantiate Grad-CAM
gradcam = TimeSformerGradCAM(clf_single)
print("Grad-CAM hooks registered on last encoder layer")

# Generate one overlay per class
panels        = []
pred_labels   = []
confidences   = []
correct_flags = []

for cls in CLASSES:
    cls_dir = os.path.join(VAL_DIR, cls)
    clips   = sorted(glob.glob(os.path.join(cls_dir, "*.mp4")))

    if not clips:
        print(f"WARNING: No clips found for '{cls}' in {cls_dir}")
        panels.append(np.zeros((SIZE, SIZE, 3), dtype=np.uint8))
        pred_labels.append("N/A"); confidences.append(0.0)
        correct_flags.append(False)
        continue

    # Try clips until one works
    panel_added = False
    for clip_path in clips[:5]:
        frames = read_clip(clip_path)
        if frames is None or len(frames) < 2:
            continue

        cls_idx = CLASSES.index(cls)
        print(f"Processing: {cls} → {os.path.basename(clip_path)}")

        try:
            pv      = preprocess_frames(frames)
            cam, pred_label, conf = gradcam(pv, target_class=cls_idx)

            # Get display frame
            disp_idx = min(FRAME_IDX, len(frames)-1)
            overlay  = make_overlay(frames[disp_idx], cam)

            panels.append(overlay)
            pred_labels.append(pred_label)
            confidences.append(conf)
            correct_flags.append(pred_label == cls)
            panel_added = True
            print(f"  → Predicted: {pred_label} ({conf:.1%}) ")
            break

        except Exception as e:
            print(f"  GradCAM error: {e}")
            continue

    if not panel_added:
        frames_fallback = read_clip(clips[0])
        if frames_fallback:
            disp = cv2.cvtColor(
                cv2.resize(frames_fallback[FRAME_IDX], (SIZE, SIZE)),
                cv2.COLOR_BGR2RGB)
        else:
            disp = np.zeros((SIZE, SIZE, 3), dtype=np.uint8)
        panels.append(disp)
        pred_labels.append("failed"); confidences.append(0.0)
        correct_flags.append(False)

gradcam.remove_hooks()

fig = plt.figure(figsize=(18, 10))
fig.patch.set_facecolor('#111111')

fig.suptitle(
    "Spatiotemporal Attention Maps Across All Seven Behaviour Classes  (TimeSformer)",
    color='white', fontsize=13, fontweight='bold', y=0.97
)

gs = fig.add_gridspec(2, 4,
                      left=0.02, right=0.88,
                      top=0.91, bottom=0.04,
                      hspace=0.38, wspace=0.08)

for i, cls in enumerate(CLASSES):
    row, col = divmod(i, 4)
    ax = fig.add_subplot(gs[row, col])
    ax.imshow(panels[i])

    # Title: class name
    ax.set_title(cls, color='white', fontsize=10,
                 fontweight='bold', pad=4)

    # Bottom: predicted label + confidence
    pred  = pred_labels[i]
    conf  = confidences[i]
    correct = correct_flags[i]
    col_pred = '#00DD77' if correct else '#FF6655'
    ax.set_xlabel(
        f"Pred: {pred} ({conf:.0%})\n{EXPECTED_REGION[cls]}",
        color=col_pred, fontsize=7, labelpad=3
    )

    ax.set_xticks([]); ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_edgecolor('#00DD77' if correct else '#FF6655')
        spine.set_linewidth(1.5)

# Hide 8th panel
ax8 = fig.add_subplot(gs[1, 3])
ax8.set_visible(False)

# Colorbar
cbar_ax = fig.add_axes([0.895, 0.15, 0.012, 0.65])
sm = plt.cm.ScalarMappable(
    cmap='jet', norm=plt.Normalize(0, 1))
sm.set_array([])
cbar = fig.colorbar(sm, cax=cbar_ax)
cbar.set_label('Attention\nintensity',
               color='white', fontsize=9, labelpad=6)
cbar.ax.yaxis.set_tick_params(color='white')
plt.setp(cbar.ax.yaxis.get_ticklabels(), color='white', fontsize=8)
cbar.set_ticks([0, 0.5, 1])
cbar.set_ticklabels(['Low', 'Mid', 'High'])

# Legend
correct_patch = mpatches.Patch(
    edgecolor='#00DD77', facecolor='none',
    linewidth=1.5, label='Correct prediction')
wrong_patch   = mpatches.Patch(
    edgecolor='#FF6655', facecolor='none',
    linewidth=1.5, label='Incorrect prediction')
fig.legend(handles=[correct_patch, wrong_patch],
           loc='lower right', bbox_to_anchor=(0.88, 0.01),
           fontsize=9, facecolor='#222222',
           labelcolor='white', framealpha=0.8)

plt.savefig(OUT_PATH, dpi=200, bbox_inches='tight',
            facecolor='#111111', edgecolor='none')
plt.show()
print(f"\nFigure saved → {OUT_PATH}")

# ── Summary ────────────────────────────────────────────────────────────────────
n_correct = sum(correct_flags)
print(f"\nResults: {n_correct}/{len(CLASSES)} classes correctly predicted")
for cls, pred, conf, ok in zip(CLASSES, pred_labels, confidences, correct_flags):
    print(f"  {cls:<26} → {pred:<26} ({conf:.1%}) {'✅' if ok else '❌'}")

import cv2
import os
from pathlib import Path


INDIVIDUAL_OUT_DIR = OUT_DIR / "individual_attention_maps"
INDIVIDUAL_OUT_DIR.mkdir(parents=True, exist_ok=True)

print(f"Saving individual overlay images to: {INDIVIDUAL_OUT_DIR}")

for i, overlay_image in enumerate(panels):
    class_name = CLASSES[i].replace(" ", "_").replace("&", "and") # Sanitize class name for filename
    filename = f"attention_map_{class_name}.png"
    filepath = INDIVIDUAL_OUT_DIR / filename

    cv2.imwrite(str(filepath), cv2.cvtColor(overlay_image, cv2.COLOR_RGB2BGR))
    print(f"Saved {filename}")

print("All individual overlay images saved!")